### ISSUE TITLE
Access to CI Pipelines

### ISSUE THREAD

**Issue by schrodit** [gardener/machine-controller-manager-provider-equinix-metal#22]
Dear Gardener CI/CD Team,

I'm on of the maintainers for the equinix extension and would like to request access for those pipelines to be able to trigger releases and hotfixes.

Kind regards,
Tim

**Comment by NiclasMoldenhauer** [comment]
Approved from management side 👍 
@zkdev Please proceed.

**Comment by zkdev** [comment]
Hi @schrodit,

I granted you access to the [corresponding pipelines](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/machine-controller-manager-provider-equinix-metal-main).

Could you please confirm that you have access and everything is working as expected?

**Comment by schrodit** [comment]
@zkdev I have access but seems like the container registry credentials are wrong. 

See https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/machine-controller-manager-provider-equinix-metal-main/jobs/main-head-update-job/builds/3
Same for the release job

Not sure if the actions are connected

**Comment by schrodit** [comment]
@zkdev fyi the job is still failing: https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/machine-controller-manager-provider-equinix-metal-main/jobs/main-head-update-job/builds/4

**Comment by zkdev** [comment]
I created PR's adjusting pipelines:
- https://github.com/gardener/machine-controller-manager-provider-equinix-metal/pull/24
- https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/302

[head-update](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/machine-controller-manager-provider-equinix-metal-main/jobs/main-head-update-job/builds/6) got green in the meantime, could you check again please :-) ?

**Comment by zkdev** [comment]
Hi @schrodit ,
is everything working as expected so we can close the issues?

**Comment by zkdev** [comment]
Pipelines are green, I am closing here.
Please get in touch in case of questions :-) .
